[package]
name = "bitrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
regex = "1"
thiserror = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
indicatif = "0.17.5"
console = "0.15.7"